on: push
jobs:
    build-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20.11.1'


            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                # caching node_modules
                path: node_modules
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-build-${{ env.cache-name }}-
                  ${{ runner.os }}-build-
                  ${{ runner.os }}-
            - name: Install Dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: npm ci

            - name: Build
              run: npm run build
            - uses: actions/cache@v2
              with:
                path: |
                  /home/runner/.nexe
                key: ${{ runner.os }}-nexe-prebuilt-${{ hashFiles('**/package.json') }}
                restore-keys: |
                  ${{ runner.os }}-nexe-prebuilt-
            - name: Publish Linux
              run: npm run publish-linux


