on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
    build-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '20.11.1'


            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                # caching node_modules
                path: node_modules
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-build-${{ env.cache-name }}-
                  ${{ runner.os }}-build-
                  ${{ runner.os }}-
            - name: Install Dependencies
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: npm ci

            - name: Build Angular UI
              run: npm run build

            - name: create release zip
              run: zip -r release.zip dist run.sh

            - name: release
              uses: actions/create-release@v1
              id: create_release
              with:
                draft: false
                prerelease: false
                release_name: Release ${{ github.ref }}
                tag_name: ${{ github.ref }}
                body_path: CHANGELOG.md
              env:
                GITHUB_TOKEN: ${{ github.token }}
            - name: upload linux artifact
              uses: actions/upload-release-asset@v1
              env:
                GITHUB_TOKEN: ${{ github.token }}
              with:
                upload_url: ${{ steps.create_release.outputs.upload_url }}
                asset_path: release.zip
                asset_name: schuetze.zip
                asset_content_type: application/gzip
